import { ServiceCategory } from "./types";

export const SERVICE_CATALOG: ServiceCategory[] = [
  {
    id: "hvac",
    name: "HVAC Services",
    icon: "Thermometer",
    services: [
      { id: "hvac-1", name: "Full AC System Installation", defaultPrice: 5500, unit: "per unit" },
      { id: "hvac-2", name: "AC Unit Replacement", defaultPrice: 3800, unit: "per unit" },
      { id: "hvac-3", name: "Furnace Installation", defaultPrice: 4200, unit: "per unit" },
      { id: "hvac-4", name: "Furnace Replacement", defaultPrice: 3500, unit: "per unit" },
      { id: "hvac-5", name: "Blower Motor Replacement", defaultPrice: 650, unit: "per unit" },
      { id: "hvac-6", name: "Freon / Refrigerant Recharge", defaultPrice: 350, unit: "per unit" },
      { id: "hvac-7", name: "Ductwork Repair", defaultPrice: 1200, unit: "flat rate" },
      { id: "hvac-8", name: "Ductwork Installation", defaultPrice: 2800, unit: "flat rate" },
      { id: "hvac-9", name: "Thermostat Installation", defaultPrice: 250, unit: "per unit" },
      { id: "hvac-10", name: "Condenser Coil Replacement", defaultPrice: 1800, unit: "per unit" },
      { id: "hvac-11", name: "Evaporator Coil Replacement", defaultPrice: 1500, unit: "per unit" },
      { id: "hvac-12", name: "HVAC System Tune-Up", defaultPrice: 180, unit: "per unit" },
    ],
  },
  {
    id: "plumbing",
    name: "Plumbing",
    icon: "Droplets",
    services: [
      { id: "plumb-1", name: "Full Re-Pipe (Copper)", defaultPrice: 8500, unit: "flat rate" },
      { id: "plumb-2", name: "Full Re-Pipe (PEX)", defaultPrice: 5500, unit: "flat rate" },
      { id: "plumb-3", name: "Water Heater Installation", defaultPrice: 1800, unit: "per unit" },
      { id: "plumb-4", name: "Tankless Water Heater Install", defaultPrice: 3200, unit: "per unit" },
      { id: "plumb-5", name: "Toilet Installation", defaultPrice: 350, unit: "per unit" },
      { id: "plumb-6", name: "Bathtub/Shower Installation", defaultPrice: 2200, unit: "per unit" },
      { id: "plumb-7", name: "Sink & Faucet Install", defaultPrice: 450, unit: "per unit" },
      { id: "plumb-8", name: "Garbage Disposal Install", defaultPrice: 280, unit: "per unit" },
      { id: "plumb-9", name: "Sewer Line Repair", defaultPrice: 4500, unit: "flat rate" },
      { id: "plumb-10", name: "Drain Cleaning", defaultPrice: 250, unit: "per visit" },
    ],
  },
  {
    id: "electrical",
    name: "Electrical",
    icon: "Zap",
    services: [
      { id: "elec-1", name: "Full Electrical Rewire", defaultPrice: 12000, unit: "flat rate" },
      { id: "elec-2", name: "Panel Upgrade (200 AMP)", defaultPrice: 2800, unit: "per unit" },
      { id: "elec-3", name: "Outlet Installation", defaultPrice: 180, unit: "per unit" },
      { id: "elec-4", name: "Light Fixture Installation", defaultPrice: 150, unit: "per unit" },
      { id: "elec-5", name: "Ceiling Fan Installation", defaultPrice: 250, unit: "per unit" },
      { id: "elec-6", name: "GFCI Outlet Install", defaultPrice: 200, unit: "per unit" },
      { id: "elec-7", name: "Smoke Detector Install", defaultPrice: 120, unit: "per unit" },
      { id: "elec-8", name: "EV Charger Installation", defaultPrice: 1500, unit: "per unit" },
    ],
  },
  {
    id: "roofing",
    name: "Roofing",
    icon: "Home",
    services: [
      { id: "roof-1", name: "Full Roof Replacement (Shingle)", defaultPrice: 9500, unit: "flat rate" },
      { id: "roof-2", name: "Roof Repair / Patch", defaultPrice: 1200, unit: "flat rate" },
      { id: "roof-3", name: "Gutter Installation", defaultPrice: 1800, unit: "flat rate" },
      { id: "roof-4", name: "Gutter Cleaning", defaultPrice: 250, unit: "per visit" },
      { id: "roof-5", name: "Fascia & Soffit Repair", defaultPrice: 1500, unit: "flat rate" },
      { id: "roof-6", name: "Skylight Installation", defaultPrice: 2200, unit: "per unit" },
    ],
  },
  {
    id: "flooring",
    name: "Flooring",
    icon: "Layers",
    services: [
      { id: "floor-1", name: "Hardwood Floor Install", defaultPrice: 8, unit: "per sqft" },
      { id: "floor-2", name: "Laminate Floor Install", defaultPrice: 5, unit: "per sqft" },
      { id: "floor-3", name: "LVP Floor Install", defaultPrice: 6, unit: "per sqft" },
      { id: "floor-4", name: "Tile Floor Install", defaultPrice: 12, unit: "per sqft" },
      { id: "floor-5", name: "Carpet Install", defaultPrice: 4, unit: "per sqft" },
      { id: "floor-6", name: "Floor Demolition", defaultPrice: 2, unit: "per sqft" },
      { id: "floor-7", name: "Hardwood Refinishing", defaultPrice: 5, unit: "per sqft" },
    ],
  },
  {
    id: "painting",
    name: "Painting",
    icon: "Paintbrush",
    services: [
      { id: "paint-1", name: "Interior Paint (per room)", defaultPrice: 450, unit: "per room" },
      { id: "paint-2", name: "Exterior Paint", defaultPrice: 4500, unit: "flat rate" },
      { id: "paint-3", name: "Cabinet Painting", defaultPrice: 2800, unit: "flat rate" },
      { id: "paint-4", name: "Deck/Fence Staining", defaultPrice: 1200, unit: "flat rate" },
      { id: "paint-5", name: "Drywall Repair & Texture", defaultPrice: 350, unit: "per area" },
    ],
  },
  {
    id: "kitchen",
    name: "Kitchen",
    icon: "ChefHat",
    services: [
      { id: "kit-1", name: "Full Kitchen Remodel", defaultPrice: 25000, unit: "flat rate" },
      { id: "kit-2", name: "Cabinet Installation", defaultPrice: 6500, unit: "flat rate" },
      { id: "kit-3", name: "Countertop Install (Granite)", defaultPrice: 4500, unit: "flat rate" },
      { id: "kit-4", name: "Countertop Install (Quartz)", defaultPrice: 5500, unit: "flat rate" },
      { id: "kit-5", name: "Backsplash Tile Install", defaultPrice: 1200, unit: "flat rate" },
      { id: "kit-6", name: "Appliance Installation", defaultPrice: 350, unit: "per unit" },
    ],
  },
  {
    id: "bathroom",
    name: "Bathroom",
    icon: "Bath",
    services: [
      { id: "bath-1", name: "Full Bathroom Remodel", defaultPrice: 15000, unit: "flat rate" },
      { id: "bath-2", name: "Shower Tile Install", defaultPrice: 3500, unit: "flat rate" },
      { id: "bath-3", name: "Vanity Installation", defaultPrice: 800, unit: "per unit" },
      { id: "bath-4", name: "Tub-to-Shower Conversion", defaultPrice: 4500, unit: "flat rate" },
      { id: "bath-5", name: "Mirror & Hardware Install", defaultPrice: 300, unit: "per set" },
    ],
  },
  {
    id: "exterior",
    name: "Exterior / Landscaping",
    icon: "Trees",
    services: [
      { id: "ext-1", name: "Siding Replacement (Vinyl)", defaultPrice: 8500, unit: "flat rate" },
      { id: "ext-2", name: "Window Installation", defaultPrice: 650, unit: "per unit" },
      { id: "ext-3", name: "Door Installation (Exterior)", defaultPrice: 900, unit: "per unit" },
      { id: "ext-4", name: "Door Installation (Interior)", defaultPrice: 350, unit: "per unit" },
      { id: "ext-5", name: "Fence Installation", defaultPrice: 3500, unit: "flat rate" },
      { id: "ext-6", name: "Concrete / Driveway Work", defaultPrice: 4500, unit: "flat rate" },
      { id: "ext-7", name: "Landscaping Package", defaultPrice: 2500, unit: "flat rate" },
      { id: "ext-8", name: "Deck Build", defaultPrice: 5500, unit: "flat rate" },
    ],
  },
  {
    id: "demolition",
    name: "Demolition & Cleanup",
    icon: "Hammer",
    services: [
      { id: "demo-1", name: "Full Interior Demo", defaultPrice: 5000, unit: "flat rate" },
      { id: "demo-2", name: "Trashout / Junk Removal", defaultPrice: 2500, unit: "flat rate" },
      { id: "demo-3", name: "Dumpster Rental (Week)", defaultPrice: 550, unit: "per week" },
      { id: "demo-4", name: "Mold Remediation", defaultPrice: 3500, unit: "flat rate" },
      { id: "demo-5", name: "Asbestos Abatement", defaultPrice: 6000, unit: "flat rate" },
    ],
  },
];
